(part "IRS-5_10-Q12P-C"
    (packageRef "IRS510Q12PC")
    (interface
        (port "1" (symbPinId 1) (portName "+VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "REM_ON/OFF") (portType INOUT))
        (port "3" (symbPinId 3) (portName "-VIN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "-VOUT") (portType INOUT))
        (port "5" (symbPinId 5) (portName "-SENSE") (portType INOUT))
        (port "6" (symbPinId 6) (portName "TRIM") (portType INOUT))
        (port "7" (symbPinId 7) (portName "+SENSE") (portType INOUT))
        (port "8" (symbPinId 8) (portName "+VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "580-IRS-5/10-Q12P-C")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Power-Solutions/IRS-5-10-Q12P-C?qs=PqoDHHvF64%2FRMwDquUqfvQ%3D%3D")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "IRS-5/10-Q12P-C")
    (property "Description" "Isolated DC/DC Converters 5V/10A 9-36Vin 1/16 brick +Log BP")
    (property "Datasheet_Link" "https://www.mouser.ph/ProductDetail/Murata-Power-Solutions/IRS-5-10-Q12P-C?qs=PqoDHHvF64%2FRMwDquUqfvQ%3D%3D")
    (property "symbolName1" "IRS-5_10-Q12P-C")
)
