(part "E48SC12030NRFH"
    (packageRef "E48SC12030NRFH")
    (interface
        (port "1" (symbPinId 1) (portName "VIN(+)") (portType INOUT))
        (port "2" (symbPinId 2) (portName "ON/OFF") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VIN(-)") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VOUT(-)") (portType INOUT))
        (port "5" (symbPinId 5) (portName "TRIM") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VOUT(+)") (portType INOUT))
        (port "7" (symbPinId 7) (portName "C2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "SIG_GND") (portType INOUT))
        (port "9" (symbPinId 9) (portName "DATA") (portType INOUT))
        (port "10" (symbPinId 10) (portName "SMBALERT") (portType INOUT))
        (port "11" (symbPinId 11) (portName "CLOCK") (portType INOUT))
        (port "12" (symbPinId 12) (portName "ADDR1") (portType INOUT))
        (port "13" (symbPinId 13) (portName "ADDR0") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Delta Electronics")
    (property "Manufacturer_Part_Number" "E48SC12030NRFH")
    (property "Description" "Isolated DC/DC Converters - Through Hole DC/DC Converter, 1/8 Brick, 12Vout, 30A")
    (property "Datasheet_Link" "https://filecenter.deltaww.com/products/download/01/0102/datasheet/DS_E48SC12030.pdf")
    (property "symbolName1" "E48SC12030NRFH")
)
